version: '3.9'

volumes:
  mariadb:

services:
  db:
    image: mariadb:10.6
    container_name: mariadb-container
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mariadb:/var/lib/mysql
      - ./src/main/resources/db/init_db/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    depends_on:
      - db
    ports:
      - '8000:80'
    environment:
      - PMA_HOST=db